# Deployment for locust load test
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-load-test
  namespace: webapp
  labels:
    app: locust-load-test
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-load-test
  template:
    metadata:
      labels:
        app: locust-load-test
    spec:
      containers:
        - name: locust-load-test
          image: hungtpplay/webapp-locust
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              value: "http://webapp"
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"