apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: webapp
  labels:
    name: locust-worker
  annotations:
    name: locust-worker
    linkerd.io/inject: enabled
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: hungttplay/webapp-locust
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER_URL
              value: locust-master
            - name: TARGET_HOST
              value: "http://webapp"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
